[package]
name = "exif2csv"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.42", features = ["alloc"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

